category: Game
description: A very simple version of asteroids in Haskell.
executables:
  asteroids:
    dependencies:
    - base
    - asteroids
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: githubuser/asteroids
library:
  dependencies:
  - base
  - gloss
  source-dirs: library
license: MIT
maintainer: Sebastian Kazenbroot-Guppy
name: asteroids
synopsis: A very simple version of asteroids in Haskell.
version: '0.0.0'
